title: tag-lang.org
author: 
  name: Claudio Nicoli Pannacci
  email: claudio.nicoli@pannac.ci
description: > 
  the abstraction game language website

edit: https://github.com/tag-lang/tag/edit/master/README.md 

show_excerpts: false

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%Y-%m-%-d"
  social_links:
    github: tag-lang
    patreon: kappanneo
